version: '1.0'
services:
  server:
    image: server
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthcheck" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
